language: java

jdk:
  - oraclejdk8

script: gradle clean test build

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:

branches:
  only:
    - master
    - development

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
